export const AUTH_TOKEN_KEY = "cc_auth_token";

export const DICE_BOX_MODULE_URL = "https://unpkg.com/@3d-dice/dice-box@1.1.3/dist/dice-box.es.min.js";
export const DICE_BOX_ASSET_PATH = "https://unpkg.com/@3d-dice/dice-box@1.1.3/assets/";

export const DEFAULT_GAME_CONFIG = {
  schema_version: "1.0",
  config_name: "Advanced Classical DDQN",
  config_description: "Default advanced single-player Scrum Game rules for the deep-RL branch.",
  players_count: 1,
  product_names: ["Yellow", "Orange", "Red", "Green", "Blue", "Purple", "Black"],
  max_turns: 6,
  starting_money: 25000,
  ring_value: 5000,
  cost_continue: 0,
  cost_switch_mid: 5000,
  cost_switch_after: 0,
  mandatory_loan_amount: 50000,
  loan_interest: 5000,
  penalty_negative: 1000,
  penalty_positive: 1000,
  daily_scrums_per_sprint: 5,
  daily_scrum_target: 12,
  board_ring_values: [
    [4, 2, 1, 1],
    [5, 3, 2, 1],
    [6, 4, 3, 2],
    [5, 3, 2, 1],
    [4, 3, 2, 1],
    [5, 3, 2, 1],
    [7, 4, 3, 2],
  ],
  board_features: [
    [3, 3, 2, 1],
    [2, 2, 1, 1],
    [1, 1, 1, 1],
    [2, 2, 2, 1],
    [3, 2, 2, 1],
    [2, 2, 1, 1],
    [1, 1, 1, 1],
  ],
  dice_rules: [
    { min_features: 1, max_features: 1, dice_count: 1, dice_sides: 20 },
    { min_features: 2, max_features: 2, dice_count: 2, dice_sides: 10 },
    { min_features: 3, max_features: null, dice_count: 3, dice_sides: 6 },
  ],
  refinement: {
    active: true,
    model_name: "Standard (ID 301)",
    die_sides: 20,
    product_rules: [
      { product_key: "yellow", increase_rolls: [1, 2], decrease_rolls: [19, 20] },
      { product_key: "orange", increase_rolls: [1, 2, 3], decrease_rolls: [19, 20] },
      { product_key: "red", increase_rolls: [1, 2], decrease_rolls: [19, 20] },
      { product_key: "green", increase_rolls: [1, 2, 3], decrease_rolls: [19, 20] },
      { product_key: "blue", increase_rolls: [1, 2, 3, 4], decrease_rolls: [19, 20] },
      { product_key: "purple", increase_rolls: [1, 2, 3], decrease_rolls: [19, 20] },
      { product_key: "black", increase_rolls: [1], decrease_rolls: [20] },
    ],
  },
  incident: {
    active: true,
    allow_player_specific_incidents: false,
    draw_probability: 1.0,
    severity_multiplier: 1.0,
    cards: [
      {
        card_id: 401,
        name: "Demand Collapse Red",
        description: "All future red sprints are worth zero.",
        effect_type: "set_future_product_to_zero",
        target_products: ["red"],
        delta_money: 0,
        target_sprint: null,
        set_value_money: null,
        future_only: true,
        weight: 1.0,
      },
      {
        card_id: 402,
        name: "New Competitors",
        description: "Orange and blue products lose value due to new competitors.",
        effect_type: "adjust_future_products",
        target_products: ["orange", "blue"],
        delta_money: -5000,
        target_sprint: null,
        set_value_money: null,
        future_only: true,
        weight: 1.0,
      },
      {
        card_id: 403,
        name: "Government Subsidy",
        description: "All first sprints gain a subsidy bonus.",
        effect_type: "adjust_specific_sprint_globally",
        target_products: [],
        delta_money: 5000,
        target_sprint: 1,
        set_value_money: null,
        future_only: true,
        weight: 1.0,
      },
      {
        card_id: 404,
        name: "Yellow Demand Boost",
        description: "All future yellow sprints gain value.",
        effect_type: "adjust_future_products",
        target_products: ["yellow"],
        delta_money: 5000,
        target_sprint: null,
        set_value_money: null,
        future_only: true,
        weight: 1.0,
      },
      {
        card_id: 405,
        name: "Black Product Breakthrough",
        description: "The fourth black sprint becomes worth 100000.",
        effect_type: "set_specific_sprint_exact",
        target_products: ["black"],
        delta_money: 0,
        target_sprint: 4,
        set_value_money: 100000,
        future_only: true,
        weight: 1.0,
      },
    ],
  },
  reserved_fields: {},
};

export const PAGES = {
  rules: {
    title: "Design",
    subtitle: "Define the blueprint the agent learns against.",
    usage: "Design uses the active blueprint and training profile.",
  },
  training: {
    title: "Train",
    subtitle: "Launch and monitor training jobs for the active workspace.",
    usage: "Train uses the active blueprint, training profile, and active brain for resume or fine-tune.",
  },
  inspect: {
    title: "Inspect",
    subtitle: "Inspect a running or finished job, run, or brain in one place.",
    usage: "Inspect follows the selected job or run and shows details, logs, and learning progress.",
  },
  evaluate: {
    title: "Evaluate",
    subtitle: "Inspect brains, compare performance, and validate blueprint fit.",
    usage: "Evaluate uses the active blueprint and active brain, while the run browser exposes historical runs and robustness jobs.",
  },
  play: {
    title: "Play",
    subtitle: "Run the arena with human and brain-controlled seats.",
    usage: "Play uses the active blueprint and active brain for model-controlled seats.",
  },
};

export const AUTO_CONNECT_URLS = [
  "http://188.166.52.37:8000",
  "http://188.166.52.37",
  "http://127.0.0.1:8000",
];
