export const state = {
  apiBaseUrl: window.location.protocol.startsWith("http")
    ? window.location.origin
    : "http://188.166.52.37:8000",
  health: null,
  gameConfigs: [],
  trainingConfigs: [],
  runs: [],
  checkpoints: [],
  jobs: [],
  activePage: "rules",
  activeGameConfigId: "",
  activeTrainingConfigId: "",
  activeCheckpointId: "",
  compatibility: null,
  activeGameConfigPayload: null,
  activeTrainingConfigPayload: null,
  visualGameConfig: null,
  playSession: null,
  directEvaluation: null,
  comparisonEvaluation: null,
  playSeatDrafts: [
    { id: "draft_1", type: "human", display_name: "Player" },
    { id: "draft_2", type: "model-expert", display_name: "AI Expert" },
  ],
  activeProgressJobId: null,
  activeProgressRunId: null,
  trainingProgress: null,
  trainingPreflight: null,
  gameConfigValidation: null,
  trainingConfigValidation: null,
  activeRunId: null,
  runDetail: null,
  activeJobDetailId: null,
  jobDetail: null,
  jobLog: null,
  progressPollHandle: null,
  includeCheckpointSelections: false,
  autopilotSettings: null,
  autopilotHistory: [],
  autopilotStopRequested: false,
  campaigns: [],
  activeCampaignId: null,
  playDiceBox: null,
  playDiceBoxReady: false,
  playDiceBoxInitPromise: null,
  runRating: null,
  messageTimer: null,
};
